### ISSUE TITLE
Invalid memory access

### ISSUE THREAD

**Issue by jwoertink** [ysbaddaden/sdl.cr#1]
I'm trying to get the [ttf sample](https://github.com/ysbaddaden/sdl.cr/blob/master/samples/16_ttf.cr) to run, but I've run in to a few issues.

1. 
```
ld: library not found for -lSDL2_ttf
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o "/Users/jeremywoertink/.cache/crystal/crystal-run-game.tmp" "${@}"  -rdynamic  -lSDL2_ttf -lSDL2 -lpcre -lgc -lpthread /usr/local/Cellar/crystal-lang/0.20.3/src/ext/libcrystal.a -levent -liconv -ldl -L/usr/lib -L/usr/local/lib`
```

I solved this one though by running `brew install sdl2_ttf`.

2.
```
Error opening file '/Users/jeremywoertink/Development/crystal/game/src/data/lazy.ttf' with mode 'rb': No such file or directory (Errno)
0x1093d7dd2: *CallStack::unwind:Array(Pointer(Void)) at ??
0x1093d7d71: *CallStack#initialize:Array(Pointer(Void)) at ??
0x1093d7d48: *CallStack::new:CallStack at ??
0x1093d38b1: *raise<Errno>:NoReturn at ??
0x1093ed921: *File#initialize<String, String, Int32, Nil, Nil>:(Event::Event | Nil) at ??
0x1093ed834: *File::new<String, String, Int32, Nil, Nil>:File at ??
0x1093efed9: *File::open<String, String, Int32, Nil, Nil>:File at ??
0x1093efec7: *File::open<String, String>:File at ??
0x109402c17: *SDL::RWops#initialize<String, String>:Pointer(Void) at ??
0x109402bd5: *SDL::RWops::new<String, String>:SDL::RWops at ??
0x109403701: *TTF::Font#initialize<String, Int32, Nil>:Bool at ??
0x1094036d3: *TTF::Font#initialize<String, Int32>:Bool at ??
0x10940368f: *TTF::Font::new<String, Int32>:TTF::Font at ??
0x1093d295c: __crystal_main at ??
0x1093d6da8: main at ??
```

Simple enough, I just changed the code to point to a .ttf file I have locally.

3.
```
Invalid memory access (signal 11) at address 0x0
[4330027003] *CallStack::print_backtrace:Int32 +107
[4330000039] __crystal_sigfault_handler +55
[140736270404538] _sigtramp +26
[4330218772] *SDL::Surface#surface:struct.LibSDL::Surface +20
[4330218558] *SDL::Surface#width:Int32 +46
[4329983124] __crystal_main +2676
[4329999784] main +40
```

I'm not sure about this error though... 
Here's the code I'm running https://gist.github.com/jwoertink/e21fda81c1c441752c8fe9c47bf83753

I'm running on macOS 10.12.2 and Crystal 0.20.3

**Comment by ysbaddaden** [comment]
1. Expected 
2. Expected 
3. SDL2 returns a NULL pointer (0x0) that isn't checked for. Can you run with `--debug` so we have line numbers in the backtrace?

**Comment by jwoertink** [comment]
hmm... I'm not seeing any additional output. Maybe I use the debug flag wrong? 

```
$ crystal build --debug src/game.cr
$ ./game
Invalid memory access (signal 11) at address 0x0
[4357443339] *CallStack::print_backtrace:Int32 +107
[4357416135] __crystal_sigfault_handler +55
[140736270404538] _sigtramp +26
[4357641348] *SDL::Surface#surface:struct.LibSDL::Surface +36
[4357641118] *SDL::Surface#width:Int32 +46
[4357399108] __crystal_main +2676
[4357415880] main +40
```

**Comment by ysbaddaden** [comment]
Argh, it's a segfault, there aren't line numbers there (to avoid more issues). Maybe `gdb` or `lldb` would have a them.

Anyway, the problem is the `@surface` pointer in a `SDL::Surface` is NULL. My guess is that `TTF#render_shaded` got a NULL pointer since there is no reason for `window.surface` to have a NULL pointer if other samples do work. But `TTF#render_shaded` does check for NULL pointers, so I don't understand how that's possible :-/

**Comment by ysbaddaden** [comment]
Oh, it may be `Window#surface`. I didn't check for NULL pointers there. I added a check in 0beae80.

**Comment by jwoertink** [comment]
Ah, ok. So now I get this: (using the debug flag)

```
SDL_GetWindowSurface: No hardware accelerated renderers available (SDL::Error)
0x10a4714c2: *CallStack::unwind:Array(Pointer(Void)) at ??
0x10a471461: *CallStack#initialize:Array(Pointer(Void)) at ??
0x10a471438: *CallStack::new:CallStack at ??
0x10a4708d1: *raise<SDL::Error>:NoReturn at ??
0x10a49de89: *SDL::Window#surface:SDL::Surface at ??
0x10a46c20f: __crystal_main at ??
0x10a4703a8: main at ??
```

My video card is NVIDIA GeForce GT 650M 1024 MB if that matters

**Comment by ysbaddaden** [comment]
One less segfault!

Now I'm afraid helping you is going to be difficult. Are other samples working? Can you run the C++ samples from http://lazyfoo.net/tutorials/SDL/ ?

**Comment by jwoertink** [comment]
Yeah, other examples work. I haven' gone through all of them, so I will now. I'll try the C++ examples and see what runs. Thanks!

**Comment by jwoertink** [comment]
I had some time to mess around with the C++ tutorial, and I was able to get the [font tutorial](http://lazyfoo.net/tutorials/SDL/16_true_type_fonts/index.php) to work. I don't really know C++, but to get it to work, I had to make sure I had `SDL2_image` and `SDL2_ttf` installed. I installed those from homebrew and included them. I'm still looking in to why this version throws the no hardware error, but just wanted to give an update that the C++ tutorials do work.

**Comment by jwoertink** [comment]
I made a change to [this line](https://github.com/ysbaddaden/sdl.cr/blob/master/samples/16_ttf.cr#L8) to
```
renderer = SDL::Renderer.new(window, SDL::Renderer::Flags::SOFTWARE | SDL::Renderer::Flags::PRESENTVSYNC)
```

I now get this error:

```
SDL_CreateRenderer: Couldn't find matching render driver (SDL::Error)
0x101a22472: *CallStack::unwind:Array(Pointer(Void)) at ??
0x101a22411: *CallStack#initialize:Array(Pointer(Void)) at ??
0x101a223e8: *CallStack::new:CallStack at ??
0x101a21881: *raise<SDL::Error>:NoReturn at ??
0x101a4ef71: *SDL::Renderer#initialize<SDL::Window, LibSDL::RendererFlags>:Nil at ??
0x101a4eeef: *SDL::Renderer::new<SDL::Window, LibSDL::RendererFlags>:SDL::Renderer at ??
0x101a1ce5d: __crystal_main at ??
0x101a21358: main at ??
```

**Comment by jwoertink** [comment]
I'm gonna close this out because "technically" the original error is fixed. I'm gonna open a new one for something else though.

**Comment by ysbaddaden** [comment]
Argh... my patch doesn't check the pointer at all :man_facepalming:

**Comment by ysbaddaden** [comment]
Maybe adding this would help on macOS?

```crystal
redefine_main(SDL_main) do |main|
  {{main}}
end
```

**Comment by jwoertink** [comment]
You're saying here? https://github.com/ysbaddaden/sdl.cr/blob/master/src/lib_sdl/main.cr#L4

**Comment by ysbaddaden** [comment]
For example, thought it must be outside of the `lib` definition, or just copy/paste it in the sample. This should call `SDL_main` which may initialize some things on macOS.
