### ISSUE TITLE
Question about movement

### ISSUE THREAD

**Issue by jwoertink** [ysbaddaden/sdl.cr#13]
I took some time to implement [sample 26](http://lazyfoo.net/tutorials/SDL/26_motion/index.php). Running this sample through Xcode works perfect and the movement is super fluid. Running my version through crystal works, but it's choppy.

Here's mine.
https://gist.github.com/jwoertink/3ecfe1f85fbe3ed2f0ff20cedeef6acc

Would you happen to know what I'm missing that makes it run smooth?

**Comment by ysbaddaden** [comment]
You are waiting for an event, which may block the loop. Maybe check whether there is an event and process it, or re-render instead?

**Comment by ysbaddaden** [comment]
The original example uses `SDL_PollEvent`.

**Comment by jwoertink** [comment]
ah! That was it. Thanks 😄
