### ISSUE TITLE
SDL_GetWindowWMInfo missing?

### ISSUE THREAD

**Issue by ReallyComeOn** [ysbaddaden/sdl.cr#23]
SDL_GetWindowWMInfo seems to be missing. Can you please add support for it?

https://wiki.libsdl.org/SDL_GetWindowWMInfo

It's useful, because it easily grants us access to the xwindow behind the SDL window.

**Comment by ysbaddaden** [comment]
Sure, pull requests are welcome.

**Comment by ReallyComeOn** [comment]
Pull request submitted.
