### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jwoertink** [ysbaddaden/sdl.cr#5]
Do you think [this module](https://github.com/ysbaddaden/sdl.cr/blob/master/src/image.cr#L4) should be namespaced to `SDL::IMG`? Same goes for the `TTF`... Even though these are separate packages, I see them more as SDL extensions. With them being packaged inside this shard, it feels like they should be within the shard's namespace.

I was gonna send a PR, but wanted to get your thoughts on that first.

**Comment by ysbaddaden** [comment]
I wondered about that when I added them, and decided to follow the C namespace. I don't have a strong opinion, and maybe it's better to put them under the `SDL` namespace, yes.

**Comment by jwoertink** [comment]
Closing this since it's merged in. Thanks!
