### ISSUE TITLE
SDL2_Mixer support

### ISSUE THREAD

**Issue by jwoertink** [ysbaddaden/sdl.cr#9]
Hey, just wanted to get your thoughts on this. I saw you sort of started to add some of this. I decided it would be a fun side project to try and learn how crystal binding work. I'm working on it in this branch https://github.com/jwoertink/sdl.cr/blob/audio/src/lib_mixer.cr, but I wanted to get your opinion on this. Is this something you would want merged in, or was there a reason you never added it? (aside from not having time to do it).

**Comment by ysbaddaden** [comment]
> Is this something you would want merged in
Of course!

**Comment by ysbaddaden** [comment]
Done.
